services:
  postgres:
    image: postgres:15-alpine
    container_name: frp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-frp_services}
      POSTGRES_USER: ${POSTGRES_USER:-frp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-frp_password}
    volumes:
      - postgres_data_3:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-frp_user}:${POSTGRES_PASSWORD:-frp_password}@postgres:5432/${POSTGRES_DB:-frp_services}
      DOMAIN: ${DOMAIN:-demycode.ovh}
      FRPS_SERVER_IPV4: ${FRPS_SERVER_IPV4}
      FRPS_SERVER_PORT: ${FRPS_SERVER_PORT}
      IPV6_SUBNET_BASE: ${IPV6_SUBNET_BASE}
      PORT: 5000
    ports:
      - "5000:5000"

  dns-server:
    build:
      context: ./dns_server
    container_name: dns-server
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      DOMAIN: ${DOMAIN:-demycode.ovh}
      FRPS_SERVER_IPV6: ${FRPS_SERVER_IPV6:-2001:db8::1}
      REGISTRATION_API_URL: http://backend:5000
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "53:53/udp"

  frps:
    build:
      context: ./frps
    ports:
      - "38000-38100:38000-38100"
      - "7000:7000"

volumes:
  postgres_data_3:
