services:
  resume-postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - /opt/data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data

    volumes:
      - /opt/data/minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  chrome:
    image: ghcr.io/browserless/chromium:v2.18.0 # Upgrading to newer versions causes issues
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TIMEOUT: 10000
      CONCURRENT: 10
      TOKEN: chrome_token
      EXIT_ON_HEALTH_FAILURE: "true"
      PRE_REQUEST_HEALTH_CHECK: "true"

  resume-app:
    container_name: resume-app
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    depends_on:
      - resume-postgres
      - minio
      - chrome
    security_opt:
      - no-new-privileges:true
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: https://resume-editor.mehdibekhtaoui.com
      STORAGE_URL: https://resume-download.mehdibekhtaoui.com/default

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://postgres:postgres@resume-postgres:5432/postgres

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

      # -- Emails --
      MAIL_FROM: noreply@localhost
      # SMTP_URL: smtp://user:pass@smtp:587 # Optional

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: "false"
      STORAGE_SKIP_BUCKET_CHECK: "false"

      DISABLE_SIGNUPS: true

      # -- Crowdin (Optional) --
      # CROWDIN_PROJECT_ID:
      # CROWDIN_PERSONAL_TOKEN:

      # -- Email (Optional) --
      # DISABLE_SIGNUPS: "false"
      # DISABLE_EMAIL_AUTH: "false"

      # -- GitHub (Optional) --
      # GITHUB_CLIENT_ID: github_client_id
      # GITHUB_CLIENT_SECRET: github_client_secret
      # GITHUB_CALLBACK_URL: http://localhost:3000/api/auth/github/callback

      # -- Google (Optional) --
      # GOOGLE_CLIENT_ID: google_client_id
      # GOOGLE_CLIENT_SECRET: google_client_secret
      # GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback

      # -- OpenID (Optional) --
      # VITE_OPENID_NAME: OpenID
      # OPENID_AUTHORIZATION_URL:
      # OPENID_CALLBACK_URL: http://localhost:3000/api/auth/openid/callback
      # OPENID_CLIENT_ID:
      # OPENID_CLIENT_SECRET:
      # OPENID_ISSUER:
      # OPENID_SCOPE: openid profile email
      # OPENID_TOKEN_URL:
      # OPENID_USER_INFO_URL:

    # nextcloud-maria-db:
    #   image: mariadb:10.6
    #   restart: always
    #   command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    #   volumes:
    #     - /opt/data/nextcloud_maria_db_data:/var/lib/mysql
    #   environment:
    #     - MYSQL_ROOT_PASSWORD=password
    #     - MYSQL_PASSWORD=password
    #     - MYSQL_DATABASE=nextcloud
    #     - MYSQL_USER=nextcloud
    #
    # nextcloud:
    #   container_name: nextcloud
    #   image: nextcloud
    #   restart: always
    #   links:
    #     - nextcloud-maria-db
    #   volumes:
    #     - /opt/data/nextcloud_data:/var/www/html
    #   environment:
    #     - MYSQL_PASSWORD=password
    #     - MYSQL_DATABASE=nextcloud
    #     - MYSQL_USER=nextcloud
    #     - MYSQL_HOST=nextcloud-maria-db
    #     - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.mehdibekhtaoui.com mehdibekhtaoui.com
    #     - APACHE_DISABLE_REWRITE_IP=1
